"""add chat actions

Revision ID: 1adaa2a9bbc0
Revises: ce1f92505be6
Create Date: 2021-05-09 13:49:08.802120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1adaa2a9bbc0"
down_revision = "ce1f92505be6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_actions",
        sa.Column("chat_action_id", sa.Integer(), nullable=False),
        sa.Column(
            "chat_action_type",
            postgresql.ENUM("create", name="chat_action_type_enum"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("chat_action_id"),
    )
    op.add_column("messages", sa.Column("action_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "messages_action_id_fkey",
        "messages",
        "chat_actions",
        ["action_id"],
        ["chat_action_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("messages_action_id_fkey", "messages", type_="foreignkey")
    op.drop_column("messages", "action_id")
    op.drop_table("chat_actions")
    op.execute("DROP TYPE chat_action_type_enum")
    # ### end Alembic commands ###
