"""split chats to direct and group and rework messages

Revision ID: 5528411a0203
Revises: 9c0f2e329761
Create Date: 2021-04-28 20:15:29.791433

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5528411a0203"
down_revision = "9c0f2e329761"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "direct_chats",
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.chat_id"],
        ),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    op.create_table(
        "group_chats",
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("admin_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.chat_id"],
        ),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    op.drop_table("text_messages")
    op.add_column("chats", sa.Column("chat_type", sa.String(), nullable=False))
    op.drop_column("chats", "title")
    op.add_column("messages", sa.Column("text", sa.String(), nullable=True))
    op.add_column(
        "messages", sa.Column("time_sent", sa.DateTime(timezone=True), nullable=False)
    )
    op.drop_column("messages", "message_type")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column("message_type", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("messages", "time_sent")
    op.drop_column("messages", "text")
    op.add_column(
        "chats", sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column("chats", "chat_type")
    op.create_table(
        "text_messages",
        sa.Column("text_message_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("message_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("text", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.message_id"],
            name="text_messages_message_id_fkey",
        ),
        sa.PrimaryKeyConstraint("text_message_id", name="text_messages_pkey"),
    )
    op.drop_table("group_chats")
    op.drop_table("direct_chats")
    # ### end Alembic commands ###
