"""add latest message to the chat

Revision ID: 56e81edb37a8
Revises: 5528411a0203
Create Date: 2021-05-04 18:19:12.733771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "56e81edb37a8"
down_revision = "5528411a0203"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("last_message_id", sa.Integer(), nullable=True))
    op.drop_constraint("chats_latest_message_id_fkey", "chats", type_="foreignkey")
    op.create_foreign_key(
        "chat_latest_message_fk",
        "chats",
        "messages",
        ["last_message_id"],
        ["message_id"],
    )
    op.drop_column("chats", "latest_message_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chats",
        sa.Column(
            "latest_message_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint("chat_latest_message_fk", "chats", type_="foreignkey")
    op.create_foreign_key(
        "chats_latest_message_id_fkey",
        "chats",
        "messages",
        ["latest_message_id"],
        ["message_id"],
    )
    op.drop_column("chats", "last_message_id")
    # ### end Alembic commands ###
