"""Add fields to user

Revision ID: 62a178ed3370
Revises: 37a57bc5c3c7
Create Date: 2021-04-17 13:44:33.018965

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "62a178ed3370"
down_revision = "37a57bc5c3c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "id", new_column_name="user_id")
    op.add_column("users", sa.Column("first_name", sa.String(), nullable=False))
    op.execute("CREATE TYPE gender_enum AS ENUM ('male', 'female')")
    op.add_column(
        "users",
        sa.Column(
            "gender",
            postgresql.ENUM("male", "female", name="gender_enum"),
            nullable=True,
        ),
    )
    op.add_column("users", sa.Column("last_name", sa.String(), nullable=False))
    op.add_column("users", sa.Column("status", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "status")
    op.drop_column("users", "last_name")
    op.drop_column("users", "gender")
    op.drop_column("users", "first_name")
    op.execute("DROP TYPE gender_enum")
    # ### end Alembic commands ###
