"""add last seen time to user

Revision ID: ce1f92505be6
Revises: f01cbfd15911
Create Date: 2021-05-08 11:15:57.623594

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ce1f92505be6"
down_revision = "f01cbfd15911"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_seen")
    # ### end Alembic commands ###
