"""Add friends

Revision ID: d5167aa20026
Revises: 62a178ed3370
Create Date: 2021-04-20 16:56:00.613742

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d5167aa20026"
down_revision = "62a178ed3370"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friends_association",
        sa.Column("first_user_id", sa.Integer(), nullable=True),
        sa.Column("second_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["first_user_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["second_user_id"],
            ["users.user_id"],
        ),
    )
    op.add_column("users", sa.Column("birthdate", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "birthdate")
    op.drop_table("friends_association")
    # ### end Alembic commands ###
