"""add latest message to the chat

Revision ID: f01cbfd15911
Revises: 5528411a0203
Create Date: 2021-05-04 21:26:14.153798

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f01cbfd15911"
down_revision = "5528411a0203"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("last_message_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "chat_last_message_fk", "chats", "messages", ["last_message_id"], ["message_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("chat_last_message_fk", "chats", type_="foreignkey")
    op.drop_column("chats", "last_message_id")
    # ### end Alembic commands ###
