version: "3.9"

services:
    db:
        ports:
            - 5432:5432

    api:
        build:
            args:
                INSTALL_DEV: ${INSTALL_DEV-true}
        volumes:
            - ./api/app:/app/app
        command: /app/start-reload.sh

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.local
        ports:
            - 3000:80
